# Generated by Django 5.0.4 on 2024-05-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Email',
            new_name='Memail',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='FullName',
            new_name='Mname',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='Phone',
            new_name='Mphone',
        ),
    ]
