# Generated by Django 5.0.4 on 2024-05-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_email_membership_memail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='membership',
            new_name='Member',
        ),
    ]
