# Generated by Django 5.0.4 on 2024-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_membership_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_pictures/'),
        ),
    ]
