# Generated by Django 5.0.4 on 2024-05-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
    ]
