# Generated by Django 5.0.4 on 2024-05-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Memail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='Mphone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(max_length=20),
        ),
    ]
