# Generated by Django 5.0.4 on 2024-05-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_member_client_alter_member_memail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
