# Generated by Django 5.0.4 on 2024-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_delete_product_delete_reservation_delete_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SportName', models.CharField(max_length=30)),
                ('nbClients', models.IntegerField()),
            ],
        ),
    ]
