# Generated by Django 5.0.4 on 2024-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='xxxxxxxx', max_length=16),
        ),
    ]
