# Generated by Django 5.0.4 on 2024-05-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_gender_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('reserved_sport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.sport')),
            ],
        ),
    ]
