# Generated by Django 5.0.4 on 2024-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_option',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
