# Generated by Django 5.0.4 on 2024-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_product_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
